name: Wx
abstract: Interface to the wxWidgets cross-platform GUI toolkit
author: Mattia Barbon <mbarbon@cpan.org>
version: 0.62
license: perl
distribution_type: module
build_requires:
  File::Spec::Functions: 0.82
  Test::More: 0.45
  Test::Harness: 2.26
  Data::Dumper: 0
  ExtUtils::MakeMaker: 6.17
  Alien::wxWidgets: 0.25
dynamic_config: 1
no_index:
  directory:
    - demo
    - samples
    - script
  package:
    - MY
    - Parse::Yapp::Driver
generated_by: Mattia Barbon, by hand
