#############################################################################
## Name:        make_exp_list.pl
## Purpose:     builds lib/Wx/_Exp.pm (export lists for Wx and Wx::Event)
## Author:      Mattia Barbon
## Modified by:
## Created:     29/10/2000
## RCS-ID:      
## Copyright:   (c) 2000 Mattia Barbon
## Licence:     This program is free software; you can redistribute it and/or
##              modify it under the same terms as Perl itself
#############################################################################

die "4 arguments required" unless @ARGV == 4;

#
# @EXPORT_OK and %EXPORT_TAGS for Wx.pm (constants in Constant.xs)
#
open IN, '< ' . $ARGV[0];

while( <IN> ) {
  m<^\s*//prefix\s+([^\s]*)\s*$> && do { $prefix = $1; next };
  m<^\s*r\w*\(\s*(\w+)\s*\);\s*(?://(.*))?$> || next;
  if( length $2 ) {
    foreach ( split '\s+', $2 ) {
      next if $_ =~ /^\s*$/;

      push @{$Wx_tag{$_}}, $prefix . $1;
    }
  }

  push @Wx_exp, $prefix . $1;
}

#
# @EXPORT_OK and %EXPORT_TAGS for Wx.pm (constants in wx/lib/Constants.pm)
#
open IN, '< ' . $ARGV[2];

while( <IN> ) {
  m/^\s*sub\s+(wx\w+)[^\}]*\}\s*(?:\#(.*))?$/ || next;
  if( length $2 ) {
    foreach ( split '\s+', $2 ) {
      next if $_ =~ /^\s*$/;

      push @{$Wx_tag{$_}}, $1;
    }
  }

  push @Wx_exp, $1;
}

#
# @EXPORT_OK for Event.pm
#

open IN, '< ' . $ARGV[1];

while( <IN> ) {
  m/sub (EVT_\w+)/ || next;
  push @Event_exp, $1;
}

close IN;

#
# write export file
#

open OUT, '> '.$ARGV[3] || die "unable to open file";

binmode OUT; # Perl 5.004 on Unix complains for CR

print OUT
  qq{#############################################################################
## Name:        _Exp.pm
## Purpose:     export lists (AUTOGENERATED, DO NOT EDIT)
## Author:      Mattia Barbon
## Modified by:
## Created:     29/10/2000
## RCS-ID:      
## Copyright:   (c) 2000 Mattia Barbon
## Licence:     This program is free software; you can redistribute it and/or
##              modify it under the same terms as Perl itself
#############################################################################

package Wx;

push \@Wx::EXPORT_OK, qw(@Wx_exp);

\$Wx::EXPORT_TAGS{everything} = [ \@Wx::EXPORT_OK ];

};

foreach ( sort keys %Wx_tag ) {
  print OUT
    qq/\$Wx::EXPORT_TAGS{$_} = [ qw(@{$Wx_tag{$_}}) ];
/;
}

print OUT
  qq{
package Wx::Event;

push \@Wx::Event::EXPORT_OK, qw(@Event_exp);
};

# Local variables: #
# mode: cperl #
# End: #

